### ISSUE TITLE
Is this still needed?

### ISSUE THREAD

**Issue by domoritz** [kantuni/arrow-js#1]
If not, maybe you can archive this repo to make it clear.

**Comment by vdonato** [comment]
Thanks for pointing this out @domoritz!

I don't believe we're still using this fork, so we should probably archive this repo.

CC @kmcgrady

**Comment by lukasmasuch** [comment]
I also think we are not using this and can - most likely - archive it.

**Comment by kmcgrady** [comment]
Going to archive it. This was no longer needed with https://github.com/streamlit/streamlit/pull/4463
